package com.pawportal.backend.models.enums;

public enum AuditAction {
    USER_LOGIN,
    USER_LOGOUT,
    USER_REGISTER,
    PASSWORD_RESET,
    PASSWORD_FORGOT,
    LOGIN_FAILED,

    USER_PROFILE_UPDATED,
    USER_PROFILE_VIEWED,
    USER_SUSPENDED,
    USER_PROMOTED,
    USER_ACTIVATED,
    USER_DELETED,

    DOG_CREATED,
    DOG_UPDATED,
    DOG_DELETED,
    DOG_VIEWED,

    APPLICATION_CREATED,
    APPLICATION_UPDATED,
    APPLICATION_VIEWED,

    CONTACT_CREATED,
    CONTACT_VIEWED,

    SYSTEM_ERROR,
    API_KEY_USED,
    SEARCH_PERFORMED
}